name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TRAINER_TOKEN_PROD }}
      TRAINER_ID: ${{ secrets.TRAINER_ID_PROD }}
      USER_LOGIN: ${{ secrets.USER_LOGIN }}
      USER_PASS: ${{ secrets.USER_PASS }}
      INCORRECT_LOGIN: ${{ secrets.INCORRECT_LOGIN }}
      INCORRECT_PASS: ${{ secrets.INCORRECT_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: pytest -v

      
